name: iit_csu_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  font_awesome_flutter: ^10.1.0
  table_calendar: ^3.0.6
  flutter:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.1.5
  flutter_secure_storage: ^5.0.2
  flutter_native_splash: ^2.2.5
  cupertino_icons: ^1.0.2

flutter_native_splash:
  color: "#4F73EF"
  image: assets/image/calendar_750.png
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
     - family: SF
       fonts:
         - asset: assets/fonts/SF-Pro-Display-Bold.otf
           weight: 700
         - asset: assets/fonts/SF-Pro-Display-Medium.otf
           weight: 500
         - asset: assets/fonts/SF-Pro-Display-Regular.otf
           weight: 400
